

[debug]
control_camera = true
use_cpu = true
manuel_tick = false
instance_rendering = true
# should be set to true, when profiling render time
vsync_off = false
print_bird_vectors = false
use_incremental_neighbor_update = false

# print debug messages?
camera_position = false
swarm_reset = true

[settings]
width = 1200
height = 800
random_seed = 110
tick = 0.0166667

[swarm]
size = 500
start = [200.0, 150.0, 0.0]
speed = 25.0

initial_spread = 40


weight_neighbours = 2.0
weight_collision = 1.0
weight_track_point = 3.0
weight_swarm_center = 2.0

[environment]
# strength
gravitation = 9.81

# position + scale
spheres = [
    [0.0, 0.0, 0.0, 1.0],
]

# values to interpolate between
[interpolation]
steps = 100

track_point = [
    [0, 0, 0],
    [0, 100, 0],
    [0, 50, 50],
    [0, 100, 0],
    [0, 50, 50],
]

# position + pitch + yaw
camera = [
    [-200, -400, 0, 1, 1],
    [-200, 30, 30, 1, 1],
    [-200, 30, 30, 1, 1],
    [-200, 30, 30, 1, 1],
    [-200, 30, 30, 1, 1],
    [-200, 30, 60, 1, 1],
    [-200, 30, 90, 1, 1],
    [-200, 30, 120, 1, 1],
    [-150, 30, 150, 1, -45],
]

# position + strength
wind = [
    [0, 1 ,0, 5],
    [1, 3 ,0, 2],
    [2, 2 ,0, 5],
    [2, 2 ,0, 5],
    [2, 2 ,0, 5],
    [2, 2 ,0, 5],
    [2, 2 ,0, 5],
    [-2, 2 ,0, 5],
]

