

[debug]
control_camera = true
use_cpu = false
manuel_tick = false
instance_rendering = true
# should be set to true, when profiling render time
vsync_off = true
print_bird_vectors = false
print_bird_debug = true
use_incremental_neighbor_update = true
skip_full_neighbor_update = true

# print debug messages?
camera_position = false
swarm_reset = true
smallest_dist = false
trace_swarm = true

[settings]
width = 1200
height = 800
random_seed = 110
tick = 0.0166667
debug_sphere_size = 25.0
follow_swarm_center = true

[swarm]
size = 1_000
start = [200.0, 150.0, 0.0]
speed = 50.0

initial_spread = 40


weight_neighbors = 1.0
weight_enemy = 1.0
weight_track_point = 1.0
weight_swarm_center = 1.0

[environment]
# strength
gravitation = 9.81

# values to interpolate between
[interpolation]
steps = 5000

# unused
ideal_distance = [
    [25, 100],
    [25, 100],
    [25, 100],
    [25, 100],
    [250, 500],
    [500, 750],
]

track_point = [
    [0, 5000, 500],
    [0, 1000, 0],
    [0, 5000, 500],
    [0, 5000, 500],
    [0, 5000, 500],
    [0, 1000, 0],
    [0, 5000, 500],
    [0, 0, 0],
    [0, 1000, 0],
    [0, 5000, 500],
    [0, 1000, 0],
    [0, 5000, 500],
    [0, 0, 0],
    [0, 1000, 0],
    [0, 5000, 500],
    [0, 1000, 0],
    [0, 5000, 500],
]

# position + scale
enemy = [
    [0.0, 0.0, 0.0, 5.0],
]

# position + pitch + yaw
camera = [
    [-150, -350, 0, 50, 10],
    [-200, -400, 0, 70, 22],
    [-200, -400, 0, 70, 22],
    [-200, -400, 0, 89, 22],
    [200, 400, 0, 89, 22],
    [200, 400, 0, 89, 22],
    [-200, -400, 0, 70, 22],
]

# position + strength
wind = [
    [0, 1 ,0, 5],
    [1, 3 ,0, 2],
    [-2, 2 ,0, 65],
    [2, 2 ,0, 30],
    [2, -2 ,0, 15],
    [2, 2 ,0, 5],
    [2, 2 ,0, 5],
    [-2, 2 ,0, 5],
    [2, 2 ,0, 5],
    [2, 2 ,0, 5],
    [2, 2 ,0, 5],
    [-2, 2 ,0, 5],
]

