

[debug]
control_camera = true
use_cpu = false
manuel_tick = false
instance_rendering = true
# should be set to true, when profiling render time
vsync_off = true
print_bird_vectors = false
use_incremental_neighbor_update = false

# print debug messages?
camera_position = false
swarm_reset = true
smallest_dist = true
trace_swarm = false

[settings]
width = 1200
height = 800
random_seed = 110
tick = 0.0166667
sphere_size = 25.0

[swarm]
size = 1_000
start = [200.0, 150.0, 0.0]
speed = 25.0

initial_spread = 40


weight_neighbors = 4.0
weight_collision = 1.0
weight_track_point = 0.5
weight_swarm_center = 1.0

[environment]
# strength
gravitation = 9.81

# position + scale
spheres = [
    [0.0, 0.0, 0.0, 1.0],
]

# values to interpolate between
[interpolation]
steps = 10000

ideal_distance = [
    [25, 100],
    [25, 100],
    [25, 100],
    [25, 100],
    [250, 500],
    [500, 750],
]

track_point = [
    [0, 5000, 500],
    [0, 1000, 0],
    [0, 5000, 500],
    [0, 5000, 500],
    [0, 5000, 500],
    [0, 1000, 0],
    [0, 5000, 500],
    [0, 0, 0],
    [0, 1000, 0],
    [0, 5000, 500],
    [0, 1000, 0],
    [0, 5000, 500],
    [0, 0, 0],
    [0, 1000, 0],
    [0, 5000, 500],
    [0, 1000, 0],
    [0, 5000, 500],
]

# position + pitch + yaw
camera = [
    [-200, -400, 0, 1, 1],
    [-200, 30, 30, 1, 1],
    [-200, 30, 30, 1, 1],
    [-200, 30, 30, 1, 1],
    [-200, 30, 30, 1, 1],
    [-200, 30, 60, 1, 1],
    [-200, 30, 90, 1, 1],
    [-200, 30, 120, 1, 1],
    [-150, 30, 150, 1, -45],
]

# position + strength
wind = [
    [0, 1 ,0, 5],
    [1, 3 ,0, 2],
    [2, 2 ,0, 5],
    [2, 2 ,0, 5],
    [2, 2 ,0, 5],
    [2, 2 ,0, 5],
    [2, 2 ,0, 5],
    [-2, 2 ,0, 5],
    [2, 2 ,0, 5],
    [2, 2 ,0, 5],
    [2, 2 ,0, 5],
    [-2, 2 ,0, 5],
]

