

[debug]
control_camera = true
use_cpu = false
manuel_tick = false
instance_rendering = true
# should be set to true, when profiling render time
vsync_off = true
print_bird_vectors = false
print_bird_debug = false
use_incremental_neighbor_update = false
skip_full_neighbor_update = true

# print debug messages?
camera_position = false
swarm_reset = true
smallest_dist = false
trace_swarm = false

[settings]
width = 1200
height = 800
random_seed = 110
tick = 0.0166667
debug_sphere_size = 25.0

[swarm]
size = 1_000
start = [0.0, 250.0, 250.0]
speed = 50.0

initial_spread = 40

# only for cpu implementation
weight_neighbors = 1.0
weight_enemy = 1.0
weight_track_point = 1.0
weight_swarm_center = 1.0

[environment]
# strength
gravitation = 9.81

# values to interpolate between
[interpolation]
steps = 100

track_point = [
    [0, 250, 250],
    [0, 250, 250],
    [0, 250, 250],
    [0, 500, 250],
    [0, 500, 250],
    [0, 500, 250],
    [0, 500, 250],
    [0, 500, 250],
    [750, 500, 500],
    [750, 500, 500],
    [750, 500, 500],
    [750, 500, 500],
    [750, 500, 500],
    [750, 500, 500],
    [750, 500, 500],
    [750, 500, 500],
    [750, 500, 500],
    [0, 500, 500],
    [0, 500, 500],
    [0, 500, 500],
    [0, 500, 500],
    [0, 500, 500],
    [0, 500, 500],
    [0, 250, 250],
]

# position + scale
enemy = [
    [-1000.0, 0.0, 0.0, 10.0],
]

# position + pitch + yaw
camera = [
    [-950, -650, 0, 40, 10],
]

# position + strength
wind = [
    [0, 1 ,0, 5],
    [0, 1 ,1, 10],
    [0, -1 , 0, 5],
    [0, -1 , -1, 15],
    [0, -1 , -1, 15],
    [0, -1 , -1, 15],
    [0, -1 , -1, 15],
    [0, -1 , -1, 15],
    [0, -1 , -1, 15],
    [0, -1 , -1, 15],
    [0, -1 , -1, 15],
    [0, -1 , -1, 15],
    [0, -1 , -1, 15],
    [0, -1 , -1, 15],
    [0, -1 , -1, 15],
    [0, -1 , -1, 15],
    [0, -1 , -1, 15],
    [0, -1, 0, 70],
    [0, -1, 0, 70],
    [0, -1, 0, 70],
    [0, 0, -1, 20],
    [0, 0, -1, 20],
    # [0, 1, 0, 20],
    [0, -1, 0, 50],
    [0, -1, 0, 50],
    [0, -1, 0, 7],
]

